
---
- name: Install apache2 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
    - name: install php
      ansible.builtin.apt:
        name: 
          - php 
          - libapache2-mod-php
          - php-mysql
        state: present
    - name: transfer information from local to remote
      ansible.builtin.copy:
        src: ./info.php 
        dest: /var/www/html/info.php 
        